name: just-build

on: 
  issue_comment:
    types: [created, edited, deleted]

jobs:
  just-build-job:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/justbuild') }}
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        conf: [Release, Debug]
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Check environment
        run: |
          gcc --version
          g++ --version
          python3 --version

      - name: Build ${{ matrix.conf }}
        run: python3 ./infra/scripts/build.py --conf ${{ matrix.conf }}

      - name: Set sattus
        run: |
          curl --request POST \
          --url https://api.github.com/repos/SamuraiCludiq/ChatLab/statuses/${{ github.sha  }} \
          --header 'content-type: application/json' \
          --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          --data '{"state": "failure","target_url": "https://example.com/build/status","description": "The tests failed!","context": "ci/tests"}'

# on:
#   pull_request:
#     types: [opened]
#   issue_comment:
#     types: [created]

# jobs:
#   just-build-job:
#     runs-on: [ubuntu-latest]
#     steps:
#       - uses: khan/pull-request-comment-trigger@v1.1.0
#         id: check
#         with:
#           trigger: '#justbuild'
#         env:
#           GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
#       - run: 'echo Found it!'
#         if: steps.check.outputs.triggered == 'true'
