name: just-build

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  just-build-job:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        conf: [Release, Debug]
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Check environment
        run: |
          gcc --version
          g++ --version
          python3 --version

      - name: Build ${{ matrix.conf }}
        run: python3 ./infra/scripts/build.py --conf ${{ matrix.conf }}
